# Site settings
title: Lompsa
description: Lompsa is an advanced multi currency crypto wallet.
baseurl: "/mofo"
url: "https://www.mofowallet.com"
twitter_username: fimkrypto
github_username:  fimkrypto
version: "0.4.10"

# Build settings
markdown: kramdown
