# Site settings
title: Mofo Wallet
description: Mofo Wallet is an advanced multi currency crypto wallet.
baseurl: "/mofo"
url: "https://www.mofowallet.com"
twitter_username: fimkrypto
github_username:  fimkrypto
version: "0.4.1"

# Build settings
markdown: kramdown
