# Site settings
title: Mofo Wallet
description: Mofo Wallet is an advanced multi currency crypto wallet.
baseurl: "/mofo"
url: "http://mofowallet.com"
twitter_username: fimkrypto
github_username:  fimkrypto

# Build settings
markdown: kramdown
