/* This file is autogenerated by the build system */
var VERSION='0.4.5';
var ENABLE_DUAL_ENGINES=true;
var IS_TEST_NET=false;
var FORCE_LOCAL_HOST=false;
var PRIVATE_ENABLED=false;
var WALLET_NAME='Mofo';
var TRADE_UI_ONLY=false;
var DEBUG=false;
