/* This file is autogenerated by the build system */
var VERSION='0.4.4';
var ENABLE_DUAL_ENGINES=false;
var IS_TEST_NET=true;
var FORCE_LOCAL_HOST=false;
var PRIVATE_ENABLED=true;
var WALLET_NAME='FIMK';
